site_name: Text-Fabric Book
site_url: https://annotation.github.io/text-fabric-book/
repo_name: 'TF book'
repo_url: https://github.com/annotation/text-fabric-book

theme: windmill

markdown_extensions:
  - toc:
      permalink: True

extra:
  logo: img/tf.png

nav:
  - Home: index.md
  - About: about.md
  - Basics:
    - Install: basics/install.md
    - Dataset: basics/dataset.md
    - Concepts: basics/concepts.md
    - Use: basics/use.md
    - Core: basics/core.md
    - Search: basics/search.md
    - Export: basics/export.md
    - Share: basics/share.md
  - Advanced:
    - Writing: advanced/writing.md
    - Interchange: advanced/interchange.md
    - TEI: advanced/tei.md
    - Pandas: advanced/pandas.md
    - Create: advanced/create.md
    - Volumes: advanced/volumes.md
    - Modify: advanced/modify.md
    - Versioning: advanced/versioning.md
  - Expert:
    - Convert:
      - Walker: expert/convert/walker.md
      - XML: expert/convert/xml.md
      - MQL: expert/convert/mql.md
    - App:
      - Settings: expert/app/settings.md
    - Static search interface:
       - Generate: expert/static/generate.md
    - Tools:
      - 'XML Schema': expert/tools/xmlschema.md
      - nbconvert: expert/tools/nbconvert.md
  - Background:
    - 'Data model': background/datamodel.md
    - 'Search engine': background/search.md
    - 'Display algorithm': background/display.md
    - 'Kernel and browser': background/server.md
  - Reference:
    - Cheatsheet: reference/cheatsheet.md
    - 'use()': reference/use.md


